### ISSUE TITLE
it crashes

### ISSUE THREAD

**Issue by inikishev** [firenh/Profundis#15]
this is what it said
```
[14:51:11] [Render thread/ERROR]: [net.minecraft.class_310#method_1514] Reported exception thrown!
net.minecraft.util.crash.CrashException: mouseClicked event handler
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:414) ~[client-intermediary.jar:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.client.Mouse.method_22686(Mouse.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.client.Mouse.method_22684(Mouse.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1244) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: Error(s) loading registries:


Errors(s) loading registry minecraft:worldgen/biome:

Optional field "music" was invalid: Failed to get element ResourceKey[minecraft:sound_event / minecraft:music.overworld.jungle_and_forest]
	at: "effects"
	at: worldgen/biome 'profundis:worldgen/biome/amethyst_caves.json'
	at: pack 'fabric'


Errors occurred freezing registries.
These were elements that were referenced, but never defined (or their definition had an error above).

Missing references from the worldgen/biome registry: [
	'profundis:amethyst_caves'
]


	at com.alcatrazescapee.cyanide.codec.MixinHooks.loadAllRegistryData(MixinHooks.java:137) ~[cyanide-fabric-1.20-4.0.0.jar:?]
	at net.minecraft.registry.RegistryLoader.handler$cff000$cyanide$loadAndReportErrors(RegistryLoader.java:1519) ~[client-intermediary.jar:?]
	at net.minecraft.registry.RegistryLoader.load(RegistryLoader.java) ~[client-intermediary.jar:?]
	at net.minecraft.server.SaveLoading.loadDynamicRegistryManager(SaveLoading.java:67) ~[client-intermediary.jar:?]
	at net.minecraft.server.SaveLoading.withRegistriesLoaded(SaveLoading.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.server.SaveLoading.load(SaveLoading.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.create(CreateWorldScreen.java:333) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget.loadLevels(WorldListWidget.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget.<init>(WorldListWidget.java:95) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.world.SelectWorldScreen.init(SelectWorldScreen.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:297) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient.java:1080) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.TitleScreen.method_19861(TitleScreen.java:159) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.TitleScreen.mouseClicked(TitleScreen.java:299) ~[client-intermediary.jar:?]
	at net.minecraft.client.Mouse.method_1611(Mouse.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:409) ~[client-intermediary.jar:?]
	... 17 more
```
https://gist.github.com/stunlocked1/7417f26334ae1e9f5b98b7fb66278b0c

**Comment by inikishev** [comment]
this also doesnt happen without cyanide
